# === Stage 72: Add Markdown report export ===
# Project: GoalTrail
def export_report(self):
    """Export goal progress as a compact Markdown report."""
    lines = []
    lines.append(f"# GoalTrail Report: {self.goal.title}")
    lines.append(f"_Status: {'Complete' if self.completed else 'In Progress'}")
    lines.append("")

    for milestone in self.milestones:
        status = "✅ Done" if milestone.done else "⬜ Pending"
        lines.append(f"- [{status}] {milestone.title}")

    for routine in self.routines:
        lines.append(f"- Routine '{routine.name}': {'done' if routine.done else 'pending'}")

    blocker_count = sum(1 for b in self.blockers if not b.resolved)
    if blocker_count:
        lines.append(f"\n**Blockers ({blocker_count}):**")
        for b in self.blockers:
            lines.append(f"- {b.description}")

    lines.append("")
    lines.append("---")
    lines.append("Generated by GoalTrail — keep going!")

    return "\n".join(lines)
